### PR TITLE
added an upload page

### PR DESCRIPTION
**Pull request by veryeasily**
boomshakalaka

### CODE REVIEW

**Comment by veryeasily** [comment]
:baby: :baby_bottle: upload.html is still just a baby, but we should merge it in

**Comment by veryeasily** [comment]
baby

**Comment by mynameisfiber** [comment]
What's going to be the difference between this and the [edit view](https://github.com/YourBrainIsAInternet/bigdipster/blob/master/templates/edit_view.html)?

**Comment by veryeasily** [comment]
Definiely, Mike just clued me into that yesterday. Closing this PR now. TTFN baby

**Pull request closed without merging**
